Use extracted parser implementation (Groonga::Log::Parser)
groonga/fluent-plugin-groonga-log pull request #2
Opened 2017-09-25 08:28 UTC by kenhys

2017-09-26 01:08 UTC, kou requested changes

2017-09-26 01:08 UTC, kou commented on fluent-plugin-groonga-log.gemspec
> +  spec.add_runtime_dependency "groonga-log", "~> 0.1"
`~> 0.1` is needless.

2017-09-26 01:08 UTC, kou commented on lib/fluent/plugin/parser_groonga_log.rb
> +        @parser.parse(StringIO.new(text)) do |statistic|
`StringIO.new()` is needless. Because `String#each_line` exists.

2017-09-26 01:08 UTC, kou commented on lib/fluent/plugin/parser_groonga_log.rb
> +          statistic.delete("time_stamp")
```ruby
time_stamp = statistic.delete("time_stamp")
event_time = Fluent::EventTime.from_time(time_stamp)
```

2017-09-26 03:14 UTC, kenhys commented
I've fixed.

* Dropped needless runtime_dependency version
* Remove needless StringIO.new
* Simplify `time_stamp` handling

2017-09-26 04:32 UTC, kou requested changes

2017-09-26 04:32 UTC, kou commented on lib/fluent/plugin/parser_groonga_log.rb
> +          time_stamp = statistic.delete("time_stamp")
"timestamp" is one word.

2017-09-26 04:32 UTC, kou commented on lib/fluent/plugin/parser_groonga_log.rb
> +        @parser = Groonga::Log::Parser.new
Namespace will be changed.

2017-09-26 05:33 UTC, kenhys commented
* Changed to `GroongaLog::Parser` namespace
* Use `timestamp` instead of `time_stamp`
* Update test case for `Interger(xxx)` and log level symbols.

2017-09-26 07:45 UTC, kenhys commented
I've fixed again.

* Use `GroongaLog::Parser` instead of `Groonga::GroongaLog::Parser`.

2017-09-27 04:53 UTC, kenhys commented
@kou could you review again?

2017-09-27 07:35 UTC, merged